name: "Um Pipeline Básico"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  hello-job:
    runs-on: ubuntu-latest

    steps:
      - name: "Checando o código"
        uses: actions/checkout@v4

      - name: "Preparando Python"
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: "Instalando dependências"
        run: python -m pip install pytest

      - name: "Dizendo Olá"
        run: echo "Olá, mundo!"

      - name: "Rodando os testes"
        run: python -m pytest tests/
      
      - name: "Mostrar informações do Sistema"
        run: |
          echo "Sistema Operacional: ${{ runner.os }}"
          echo "Versão do Python: $(python --version)"
          echo "Data e Hora: $(date)"
      
      - name: "Lista aquivos do repositório"
        run: ls -la

      - name: "Comandos avançados"
        run: |
          echo "Criando um arquivo de teste..."
          echo "Este é um arquivo de teste." > teste.txt
          cat teste.txt
          rm teste.txt

      - name: "Gerar artefato"
        run: |
          echo "Gerando um artefato de exemplo..."
          echo "Este é um artefato de exemplo." > artefato.txt
          cat artefato.txt
